# Generated by Django 3.0.2 on 2020-01-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_img', models.ImageField(upload_to='')),
                ('meme_name', models.CharField(max_length=50)),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemesInDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=1000)),
                ('meme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memexicon.Memes')),
            ],
        ),
    ]
