# Generated by Django 3.0.2 on 2020-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memexicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='meme_img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
